blank_issues_enabled: false

contact_links:
  - name: Ask a question or get help
    url: https://github.com/your-org/your-repo/discussions
    about: Use GitHub Discussions to ask questions and get support

